steps:
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE}
      - --source=./server
      - --region=${_REGION}
      - --allow-unauthenticated
      - --max-instances=1
      - --clear-base-image

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _REGION: asia-east1
  _SERVICE: bountyface-backend
